// Fictional content for interaction and layout testing. These are not live listings.
// Keep this separate so the team can replace activities with a BCC API adapter later.
const activities = [
  { id: 'park', title: 'A morning of play in the park', category: 'Outdoors', suburb: 'New Farm', venue: 'New Farm Park', day: 'Saturday', time: '9:00 am – 11:00 am', cost: 0, ages: 'All ages', weekend: true, description: 'Pack a picnic and enjoy an easy morning outdoors with the family. This example shows where activity details, accessibility and booking information will appear.' },
  { id: 'market', title: 'Family preloved & makers market', category: 'Markets & secondhand', suburb: 'West End', venue: 'Community market space', day: 'Sunday', time: '8:00 am – 12:00 pm', cost: 0, ages: 'All ages', weekend: true, description: 'An example market listing for browsing preloved clothing, toys and household finds. Free entry does not include purchases at stalls.' },
  { id: 'stories', title: 'Little readers: storytime', category: 'Libraries', suburb: 'Brisbane City', venue: 'Brisbane Square Library', day: 'Tuesday', time: '10:00 am – 10:45 am', cost: 0, ages: 'Ages 0–5', weekend: false, description: 'A sample library activity with stories, songs and a chance to meet other families. Actual sessions and availability will come from council data.' },
  { id: 'craft', title: 'Make something from something', category: 'Creative', suburb: 'West End', venue: 'Community hall', day: 'Saturday', time: '10:00 am – 12:00 pm', cost: 5, ages: 'Ages 5–12', weekend: true, description: 'A sample hands-on session turning reusable materials into a small craft project. Cost is shown per participant in this wireframe.' },
  { id: 'garden', title: 'Little explorers garden walk', category: 'Outdoors', suburb: 'Toowong', venue: 'Local gardens', day: 'Sunday', time: '9:30 am – 10:30 am', cost: 0, ages: 'Ages 3–8', weekend: true, description: 'A sample guided nature activity. The final event page should confirm walking distance, shade, facilities and whether bookings are required.' },
  { id: 'swap', title: 'Community toy & book swap', category: 'Markets & secondhand', suburb: 'New Farm', venue: 'Neighbourhood centre', day: 'Wednesday', time: '3:00 pm – 5:00 pm', cost: 0, ages: 'All ages', weekend: false, description: 'A sample reuse event where families can exchange books and toys. This is an event concept, not a connected secondhand marketplace.' }
];

const initialPosts = [
  { id: 'p1', author: 'Alex M.', initials: 'AM', suburb: 'New Farm', time: '2 hours ago', category: 'Meetups', title: 'Anyone up for a park morning this weekend?', body: 'We’re planning a picnic and a bit of playground time with our two little ones. Would love to meet some other local families. Bring your own snacks and come say hello!', eventId: 'park', helpful: 12, replies: [{ author: 'Sam R.', text: 'A picnic sounds lovely! Is there a shaded spot near the playground?' }, { author: 'Alex M.', text: 'Let’s meet by the covered picnic area. Everyone is welcome.' }] },
  { id: 'p2', author: 'Jordan L.', initials: 'JL', suburb: 'West End', time: '4 hours ago', category: 'Local tips', title: 'Your favourite free rainy-day activities?', body: 'Looking for ideas for a rainy weekend with a 4-year-old and a 7-year-old. Libraries are already on our list. What else do your families enjoy without spending much?', helpful: 8, replies: [{ author: 'Taylor K.', text: 'We make an indoor treasure hunt with things we already have at home.' }] },
  { id: 'p3', author: 'Casey T.', initials: 'CT', suburb: 'Toowong', time: 'Yesterday', category: 'Swap & share', title: 'A book swap for the kids — who’s interested?', body: 'Our children have outgrown a few picture books. Would anyone like to organise a small swap at a local community space? A nice way to give books another chapter.', helpful: 6, replies: [] }
];
